name: Publish on Release

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Ruff check
        run: |
          poetry run ruff format --check
          poetry run ruff check .
      - name: Run tests with pytest
        run: poetry run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: pypi
      url: https://pypi.org/project/ohlc-toolkit
    permissions:
      id-token: write # Note: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install build and publish dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build package
        run: |
          poetry build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
