# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  # Trigger the workflow only for pull requests for the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Ruff check
        run: |
          poetry run ruff format --check
          poetry run ruff check .
      - name: Run tests with pytest
        run: poetry run pytest

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ohlc-toolkit
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install build and publish dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build package
        run: |
          poetry build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
