name: Test and Publish

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Ruff check
        run: |
          poetry run ruff format --check
          poetry run ruff check .

      - name: Run tests with pytest
        run: poetry run pytest --cov=ohlc_toolkit --cov-report=xml

      - name: Upload coverage to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ohlc-toolkit
    permissions:
      id-token: write # Note: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build and publish dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build package
        run: |
          poetry build

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
